replicaCount: 2
name: web-app
serviceAccountName: web-app-sa
labels:
  app: web-app
  environment: dev

selectorLabels:
  app: web-app

image:
  name: ghcr.io/mavbharath/python-ap
  tag: 0.0.1
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  nodePort: 30088

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
